version: "3.1"
services:
  react:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: React_smart_koshk_container
    volumes:
      - ./src:/React_smart_koshk/src:ro
    ports:
      - "3061:3061"
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    build:
      context: ./
      dockerfile: Dockerfile.nginx
    # volumes:
    #     - ./Care_Frontend/build:/usr/share/nginx/html:ro
    ports:
      - 87:80
    restart: always
